### ISSUE TITLE
Ideas for 2017

### ISSUE THREAD

**Issue by lucywyman** [DevOpsBootcamp/website#116]
SUMMER BEFORE: Ask alum if they would be willing to write x-many recommendations for BootCamp graduates for internships over the summer.  Then, if students go to x-many sessions per term (8-9), then we will recommend them for an internship at a company of their choice from list.

**Comment by ElijahCaine** [comment]
I had also thought a good sanity check would be to ask industry folks (maybe the same ones we ask for recommendations) what our curriculum should over each year, giving them what we currently cover and asking for improvements.

>"Hey Industry Person, we currently cover XYZ as far as development and ABC as far as ops, in these IJK ways. As someone that recruits interns and employees what skills do you think would help new hires as they enter your workforce? 

This would make it very easy to continue to sell DOBC as 'A great thing to put on your resume', which may or may not help retention.

There's a lot of things I know we don't cover as well as we could (how to use github/git for instance), and some direction would be helpful going forward.

**Comment by lucywyman** [comment]
Oo, that's definitely a good idea.  Should we do it as a form, like "Here's a list of our current topics, for more info here's a link to our slides, we are thinking about adding content X, Y, Z, Nothing it's perfect, or OTHER (fill in the blank)" and have a section for comments.  My only thinking is that I'm more likely to fill out a form than to take the time to write out a response, but that still gives people the option of writing to us.

**Comment by borcean** [comment]
Definitely, having a Google Form for submitting feedback would be ideal both in making it easier for people to communicate with us as well as for keeping all of their responses organized so we can see trends in their requests. 

Wasn't git covered a bit last term? If not it would definitely be a smart addition to both dev and ops curriculum. :smile:

**Comment by ElijahCaine** [comment]
@borcean We cover a lot of topics very just a little bit (like git and github, we mention it exists and talk about some commands to use it, but that's about it). So deciding based on feedback from alum and industry folks what to put more resources into would help making it marketable.

The form should look something like this: http://goo.gl/forms/FMoSYpOA7H but with more going on. That's just a rough draft.

**Comment by lucywyman** [comment]
One idea I had was, instead of saying "What curriculum should dobc have", we could ask "What skills do you consider essential or very valuable to your job? What tools, methodologies, or frameworks do you use frequently?"

**Comment by lucywyman** [comment]
@ElijahCaine @borcean @tschuy I updated the google form (http://goo.gl/forms/FMoSYpOA7H) -- let me know what you think, and if I don't hear back I plan to send it out tomorrow at noon.  Thanks!

**Comment by ElijahCaine** [comment]
@lucywyman The 'option 1' at the end doesn't seem like it should be there, but the rest of the form you linked looks good.
