### ISSUE TITLE
review version control lesson

### ISSUE THREAD

**Issue by Kennric** [DevOpsBootcamp/website#125]

**Comment by codymalick** [comment]
I'm combing through this one now. Doesn't look like I can assign myself to this, so dibs.

**Comment by aaroncohen73** [comment]
@codymalick You have to accept the invitation that I sent you before I can assign the issue

**Comment by codymalick** [comment]
Would you look at that. Thanks!

**Comment by codymalick** [comment]
Couple notes:
- The git lesson covers how to branch, clone, etc., but doesn't actually have the user do any of these things beyond cloning the flask app. Might consider doing a little more hands on once the repo is clone.
- Overall the lesson is very good. I think it's rather short for such an important topic, but we should work out about how long the section takes to run through with a novice audience.

**Comment by aaroncohen73** [comment]
If we can get some novices to attend the rehearsal, we could use their feedback to improve the lesson before the main event. Otherwise, we should take notes and gather feedback at the November 5th session.

**Comment by codymalick** [comment]
Maybe we could add something that would clearly show how branching, merging, commits, etc. work. This is a great tool for things like that:
http://learngitbranching.js.org/

**Comment by codymalick** [comment]
Possibly add content to cover Github tools.
