### ISSUE TITLE
Plan future DOBC sessions

### ISSUE THREAD

**Issue by aaroncohen73** [DevOpsBootcamp/website#140]
@leian7 @Kennric @kelnera 

We need to figure out scheduling for sessions this term. Due to prior arrangements, I wouldn't be available on the first Saturday of February, so if we wanted to keep DOBC happening at roughly the same time each month we would need to choose a Saturday other than the first one.

This is my proposed schedule for Winter Term 2017:

| Session Name | Session Date | Topics Covered |
|--------------------|------------------|----------------------|
| Winter Term 1 | January 28, 2017  | Security, Databases |
| Winter Term 2 | February 25, 2017 | Dev Processes & Tools, DNS, Configuration Management |

**Comment by kelnera** [comment]
I don't see any issues. I'll check with KEC scheduling. Hopefully we won't have a repeat of last event.

**Comment by aaroncohen73** [comment]
Closing since DOBC has concluded for the remainder of the academic year
