### ISSUE TITLE
useful devops life skills notes

### ISSUE THREAD

**Issue by edunham** [DevOpsBootcamp/website#21]
having a conversation with some higher-ups at my internship about training programs such as DOBC. 

their points:

"if you mention timezones and someone is all "oh i got that" then you know they're either a) lying or b) unaware "

" backups that aren't tested regularly aren't backups (that's a painful one to learn in the field) "

"character encodings are death on a stick "

"in general, any place where the "obvious" parts of daily life enter a computer. e.g., a database scheme for people that includes their names. first and last? middle initial? jr. sr.? madonna? "

"logging only seems useless when things aren't on fire, ditto for tests and quick deploys. Never assume small changes will only break small things. No matter how minor something seems to be never make the change directly to production. "

" oh and no matter how shiny and nice your ORM is if you don't know where the slow query log is you are fucked "

http://ptgmedia.pearsoncmg.com/images/9780134769042/samplepages/013476904X.pdf good for OOP learning

**Comment by lucywyman** [comment]
Can I close this issue?  It will still be in 'closed issues' for posterity, but I don't think there are any actionable items (buzzword buzzword) included.
