### ISSUE TITLE
Improve documentation on how to install git

### ISSUE THREAD

**Issue by ramereth** [DevOpsBootcamp/website#25]
Using git is very important and we need clear docs on how to do it on the various platforms students may have. Lets work on a doc that covers Windows, Mac and Linux.

**Comment by iankronquist** [comment]
There is also github for mac. I know we are trying to push people to use the CLI version of git, but I'm sure github has done their job and it probably works on many versions of OSX.

**Comment by ElijahCaine** [comment]
This was resolved with PR #61, however we will keep this issue around for potential improvement of Git documentation.
