### ISSUE TITLE
Archive by year

### ISSUE THREAD

**Issue by lucywyman** [DevOpsBootcamp/website#95]
Menu structure:

DevOps BootCamp:
    2015
         Lesson 1
         Lesson 2
    2014
         Lesson 1
         Lesson 2

**Comment by ElijahCaine** [comment]
If we organize DOBC like this we should also organize Videos, Daycamp Content, and Slides like this. Thoughts?

**Comment by lucywyman** [comment]
I like it -- it feels more sustainable and organized than how we currently have it.  @jordane @borcean @tschuy ?

**Comment by ElijahCaine** [comment]
Here is the general structure of what the sidebar will look like:
```
devops bootcamp
    Lesson 1
    Lesson 2
    ....
devops daycamp
    Lesson A
    Lesson B
    ...
archive
    2015-2014
        devops daycamp
        devops bootcamp
    2014-2013
        devops bootcamp
```
The Bootcamp and Daycamp pages will look about the same as they do now.
The Archive page will have this approximate structure:
```
Archive
    h1: 2015-2014
        h2: devops daycamp
            h3: lesson A
                content [link]
                Video [link]
                Activity [link][if there is an activity]
            h3: lesson B
                content [link]
                Video [link]
                Activity [link][if there is an activity]
            ...
        h2: devops bootcamp
            h3: lesson 1
                content [link]
                Video [link]
                Activity [link][if there is an activity]
            h3: lesson 2
                content [link]
                Video [link]
                Activity [link][if there is an activity]
            ...
```

Does this about line up with what you imagined @lucywyman ?

**Comment by lucywyman** [comment]
This isn't per se difficult, but is more nontrivial than just using toctrees. We can make templates for the archive pages so that the lessons are automagically populated as done above, which I actually really like. I'll try to do that in the next week.
